### PR TITLE
Add support media control, and fix position track

### PR DESCRIPTION
**Pull request by Aleks130699**
Add support play(resume), pause, next, prev, and fix show position track

### CODE REVIEW

**Comment by madsci1016** [comment]
@koolsb  are you still maintaining this repo? This pull request looks good plus the manifest.json needs some updates as HA updates have broken the integration as it stands here.

**Comment by Aleks130699** [comment]
@madsci1016 You can use my repository, all problems have been fixed in it , in particular with the current version of ha https://github.com/Aleks130699/ha-fpp

**Comment by GizmoGoody** [comment]
@Aleks130699 I switched to your repo. It seems to be working about the same as what I had on the main branch, but I was hoping it would also add the media_title which currently shows as an empty string for me. Any chance you could address that? I would have submitted this request on your branch, but don't think GitHub provides a place to enter issues/requests on forks.

BTW, thanks for taking this repo on!

image

**Comment by Aleks130699** [comment]
> @Aleks130699 Я переключился на ваш репозиторий. Кажется, это работает примерно так же, как то, что у меня было в основной ветке, но я надеялся, что это также добавит media_title, который в настоящее время отображается для меня как пустая строка. Есть ли шанс, что вы могли бы решить эту проблему? Я бы отправил этот запрос в вашу ветку, но не думаю, что GitHub предоставляет место для ввода проблем / запросов в форках.
> 
> Кстати, спасибо, что приняли это репо!
> 
> изображение

**Comment by Aleks130699** [comment]
@GitHubGoody It's strange, I have data displayed there, could you show me how it looks on the itself fpp, You could also check what this page "/api/fppd/status" gives on fpp, the current track being played should be displayed in "current_sequence", perhaps the player itself does not give this data or elsewhere

**Comment by GizmoGoody** [comment]
Ah, I think I see what's going on. I'm playing a playlist made up of only Single File .mp4's (no sequences).

image

So, if the HA media_title attribute is mapped to the FPP current_sequence key, it comes up blank for non-sequences.

{"MQTT":{"configured":false,"connected":false},"bridging":false,"current_playlist":{"count":"5","description":"","index":"2","playlist":"Christmas","type":"media"},"current_sequence":"","current_song":"ChristmasToyTinkering.mp4","dateStr":"Tue Dec 12","fppd":"running","mode":2,"mode_name":"player","multisync":false,"next_playlist":{"playlist":"Christmas","start_time":"Tue Dec 12 @ 05:11 PM - (Everyday)"},"repeat_mode":0,"scheduler":{"currentPlaylist":{"playlistName":"Christmas"},"enabled":1,"nextPlaylist":{"playlistName":"Christmas","scheduledStartTime":0,"scheduledStartTimeStr":"Tue Dec 12 @ 05:11 PM - (Everyday)"},"status":"manual"},"seconds_elapsed":"39","seconds_played":"39","seconds_remaining":"76","sensors":[{"formatted":"35.2","label":"CPU: ","postfix":"","prefix":"","value":35.241999999999997,"valueType":"Temperature"}],"status":1,"status_name":"playing","time":"Tue Dec 12 07:59:07 EST 2023","timeStr":"07:59 AM","timeStrFull":"07:59:07 AM","time_elapsed":"00:39","time_remaining":"01:16","uptime":"03:57:32","uptimeDays":0.16495370370370371,"uptimeHours":3.9588888888888887,"uptimeMinutes":57.533333333333331,"uptimeSeconds":32,"uptimeStr":"0 days, 3 hours, 57 minutes, 32 seconds","uptimeTotalSeconds":14252,"uuid":"M1-00000000bb11ff10","volume":40}

But, I do see that the current_song key does contain what I'd like to see for media_title. Any chance your integration could conditionally map that key instead for these situations?

**Comment by Aleks130699** [comment]
@GitHubGoody Understood, yes, because you only have a video file playing, then the current name of the playback is in another parameter, you can try in the file "/homeassistant/custom_components/falcon_pi_player/media_player.py "in line 81, replace "self._media_title = status["current_sequence"].replace(".fseq", "") " to " self._media_title = status["current_song"] "

Unfortunately, I don't have the opportunity to test and correct the code right now, so I suggest this variation for you
In theory, this should work for sequences as well, but most likely only those with a video or audio file

**Comment by GizmoGoody** [comment]
Thanks. This does the trick for what I need:
`self._media_title = status["current_song"].replace("Halloween","").replace("Thanksgiving","").replace("Christmas","").replace(".mp4","")`

image

While I'm configuring it though, I'd also like to change the default media_player icon, but cannot since it doesn't have a unique id. So, I tried to add that to my configuration like other templates.

```
- platform: falcon_pi_player
  name: Falcon Player
  host: 192.168.0.229
  unique_id: "falcon_player"
```

But, I get this error when I check the configuration:
`Invalid config for [media_player.falcon_pi_player]: [unique_id] is an invalid option for [media_player.falcon_pi_player]. Check: media_player.falcon_pi_player->unique_id. (See ?, line ?).`

Any idea why?

**Comment by Aleks130699** [comment]
@GitHubGoody At the moment, this integration cannot accept this parameter, I tried to add it now, but I do not have enough knowledge in the development of integrations, and I have not succeeded yet

**Comment by Aleks130699** [comment]
@GitHubGoody But no, I found a simple way, which it turns out I already did, I need to add another after line 66 `self._attr_unique_id = "media_player_{name}"`
You do not need to specify the unique_id manually

**Comment by GizmoGoody** [comment]
I get this when I try to edit the media_player entity in the UI:

image

**Comment by Aleks130699** [comment]
@GitHubGoody Did you add this line? and after that, you need to reboot the HA
image

**Comment by GizmoGoody** [comment]
That worked great. Sorry, I misunderstood your earlier reply.

Last thing. Is there any album art that can be exposed through this from Falcon Player?

**Comment by Aleks130699** [comment]
@GitHubGoody Great, about the covers, I think not, since fpp does not give such data

**Comment by GizmoGoody** [comment]
NP. For the couple changes I made (media title and unique ID), should I just maintain this separately in my HA instance or do you think you'll need to make more changes in the future meaning you would incorporate these changes as well?

**Comment by Aleks130699** [comment]
@GitHubGoody In the future, of course, I will make these changes, perhaps with a slightly different implementation, but at the moment there is no way to test all this on real hardware, because there will be no changes in the near future (perhaps except for the unique identifier), you can safely leave the changes as they are

**Comment by Aleks130699** [comment]
@GitHubGoody I have released a new version of the fpp client, in which I have made some changes to improve its operation, you can check it out. https://github.com/Aleks130699/ha-fpp/releases/tag/v1.1.2

**Comment by Aleks130699** [comment]
@GitHubGoody The beta version:

Added the ability to use covers:
To do this, you need to add jpg images to the image item on the fpp player through the File Manager, the file name must exactly match the file being played, replacing the extension. ".fseq", ".mp3" or ".mp4" to ".jpg"

https://github.com/Aleks130699/ha-fpp/releases/tag/v1.1.3-dev

You can test this release

**Comment by GizmoGoody** [comment]
Nice. Honestly, I probably won't mess with FPP again until ~Sept-Oct, but I look forward to these new features. Thank you!

**Pull request closed without merging**
